name: Releases

on: 
  push:
    tags:
    - '*'
  workflow_dispatch: 

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn install

    - name: Build plugin
      run: yarn build

    - name: Install zip
      uses: montudor/action-zip@v1
    
    - name: Pack plugn
      run: zip -qq -r ../plugin.ccx *
      working-directory: dist
      
    - name: Send release mail
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{secrets.MAIL_CONNECTION}}
        subject: New version of AMEA Photoshop Plugin
        to: ${{secrets.MAIL_RECIPIENTS}}
        from: AMEA Photoshop Plugin
        body: There is anew version of AMEA Photoshop Plugin. Make sure to check it out!
        attachments: plugin.ccx

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: plugin.ccx
        generate_release_notes: true
