name: Releases

on: 
  push:
    tags:
    - '*'
  workflow_dispatch: 

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn install

    - name: Build plugin
      run: yarn build

    - name: Install zip
      uses: montudor/action-zip@v1
    
    - name: Pack plugn
      run: zip -qq -r plugin.ccx *
      working-directory: dist

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: plugin.ccx
        generate_release_notes: true
